Repository Azure-Samples/azure-ml-federated-learning, pull requests merged in 2022-10, with the labels that each got.

#107 Fix and clean-up of open sandbox provisioning scripts, align submit scripts
  examples/components/HELLOWORLD/aggregatemodelweights/run.py
  examples/pipelines/fl_cross_silo_factory/config.yaml
  examples/pipelines/fl_cross_silo_factory/submit.py
  examples/pipelines/fl_cross_silo_native/config.yaml
  mlops/bicep/modules/permissions/msi_storage_rw.bicep
  mlops/bicep/modules/resources/open_azureml_workspace.bicep
  mlops/bicep/modules/resources/open_compute_storage_pair.bicep
  mlops/bicep/modules/silos/open_internal_blob.bicep
  mlops/bicep/open_sandbox_setup.bicep
Labels: bug

#108 Rename "native" submission script to "literal" (keep native for our end goal integration FL API)
  .github/workflows/python.yaml
  docs/quickstart.md
  examples/pipelines/fl_cross_silo_literal/config.yaml
  examples/pipelines/fl_cross_silo_literal/environment.yml
  examples/pipelines/fl_cross_silo_literal/requirements.txt
  examples/pipelines/fl_cross_silo_literal/submit.py
Labels: documentation

#109 Add shortcut to quickstart from README
  README.md
Labels: documentation

#113 Update quickstart to mention rg clean-up
  docs/quickstart.md
Labels: documentation

#95 Example of "eyes-off" provisioning with vnet
  docs/quickstart.md
  mlops/bicep/modules/networking/nsg.bicep
  mlops/bicep/modules/networking/private_endpoint.bicep
  mlops/bicep/modules/networking/vnet.bicep
  mlops/bicep/modules/networking/vnet_peering.bicep
  mlops/bicep/modules/resources/storage_private.bicep
  mlops/bicep/modules/resources/vnet_compute_storage_pair.bicep
  mlops/bicep/vnet_publicip_sandbox_setup.bicep
Labels: auto-provisioning

#122 Add subscription id, resource group and workspace name as CLI args
  docs/quickstart.md
  examples/pipelines/fl_cross_silo_factory/submit.py
  examples/pipelines/fl_cross_silo_literal/submit.py
Labels: enhancement, iteration-03

#119 Continuous Integration Tests
  .github/actions/provision-resources/action.yaml
  .github/actions/submit-aml-factory-pipeline/action.yaml
  .github/actions/submit-aml-literal-pipeline/action.yaml
  .github/scripts/delete-run-history.sh
  .github/workflows/build-test.yaml
  .github/workflows/clear-pipeline-run-history.yaml
  .github/workflows/pipeline-e2e-test.yaml
  .github/workflows/release-branch-test.yaml
  examples/pipelines/fl_cross_silo_factory/submit.py
  examples/pipelines/fl_cross_silo_literal/submit.py
  mlops/bicep/open_sandbox_setup.bicep
  mlops/bicep/vnet_publicip_sandbox_setup.bicep
Labels: iteration-03, testing

#128 Add vnet-based provisioning options to cookbook
  docs/pics/vnet_silo_provisioning.png
  docs/provisioning/README.md
  docs/provisioning/orchestrator_open.md
  docs/provisioning/silo_open.md
  docs/provisioning/silo_vnet_newstorage.md
  mlops/arm/vnet_compute_storage_pair.json
  mlops/arm/vnet_publicip_sandbox_setup.json
  mlops/bicep/modules/resources/vnet_compute_storage_pair.bicep
  mlops/bicep/vnet_publicip_sandbox_setup.bicep
Labels: auto-provisioning

#135 Make deployment name unique in our github actions
  .github/actions/provision-resources/action.yaml
  .github/workflows/pipeline-e2e-test.yaml
  .github/workflows/release-branch-test.yaml
Labels: bug

#136 Provide motivation in provisioning docs for using service endpoints
  docs/provisioning/silo_vnet_newstorage.md
Labels: documentation, auto-provisioning

#139 Refresh provisioning arm buttons with latest from bicep
  docs/provisioning/silo_open.md
  docs/provisioning/silo_vnet_newstorage.md
  mlops/arm/open_compute_storage_pair.json
  mlops/arm/open_sandbox_setup.json
  mlops/arm/vnet_compute_storage_pair.json
  mlops/arm/vnet_publicip_sandbox_setup.json
Labels: bug, documentation, auto-provisioning

#140 Add Bicep build vs ARM template diff test
  .github/actions/bicep-to-arm-template-diff/action.yaml
  .github/workflows/pipeline-e2e-test.yaml
  .github/workflows/release-branch-test.yaml
Labels: iteration-03, testing

#138 Add "open aks with cc" provision tutorial and bicep scripts
  docs/provisioning/README.md
  docs/provisioning/silo_open_aks_with_cc.md
  mlops/arm/open_aks_with_confcomp_storage_pair.json
  mlops/bicep/modules/azureml/attach_aks_training_to_azureml.bicep
  mlops/bicep/modules/azureml/deploy_aks_azureml_extension.bicep
  mlops/bicep/modules/azureml/deploy_aks_azureml_extension_via_script.bicep
  mlops/bicep/modules/computes/open_new_aks_with_confcomp.bicep
  mlops/bicep/modules/fl_pairs/open_aks_with_confcomp_storage_pair.bicep
Labels: enhancement, auto-provisioning

#142 Provide script + tutorial to attach pair with an existing storage
  docs/provisioning/README.md
  docs/provisioning/silo_vnet_existingstorage.md
  docs/provisioning/silo_vnet_newstorage.md
  mlops/arm/vnet_compute_existing_storage.json
  mlops/bicep/modules/fl_pairs/vnet_compute_existing_storage.bicep
  mlops/bicep/modules/storages/existing_blob_storage_datastore.bicep
Labels: auto-provisioning

#145 Add recent arm templates to diff build
  .github/workflows/pipeline-e2e-test.yaml
Labels: auto-provisioning

#149 Update silo creation tutorials to integrate feedback (schema update, orchestrator endpoints, ...)
  docs/pics/vnet_silo_provisioning.png
  docs/provisioning/silo_vnet_existingstorage.md
  docs/provisioning/silo_vnet_newstorage.md
Labels: auto-provisioning
