Repository Azure-Samples/azure-ml-federated-learning, pull requests merged in 2022-11, with the labels that each got.

#131 Add silo/training subgraph for a better UX
  examples/components/HELLOWORLD/traininsilo/run.py
  examples/components/HELLOWORLD/traininsilo/traininsilo.yaml
  examples/components/MNIST/traininsilo/run.py
  examples/components/MNIST/traininsilo/traininsilo.yaml
  examples/pipelines/fl_cross_silo_factory/fl_factory.py
  examples/pipelines/fl_cross_silo_factory/requirements.txt
  examples/pipelines/fl_cross_silo_factory/submit.py
  examples/pipelines/fl_cross_silo_literal/requirements.txt
  examples/pipelines/fl_cross_silo_literal/submit.py
Labels: iteration-03

#166 Hotfix: grant `az login` permissions to the 'clear run history' script
  .github/workflows/clear-pipeline-run-history.yaml
Labels: bug, iteration-04

#181 Finance: Credit card fraud detection using FL pipeline
  docs/README.md
  docs/real-world-examples/ccfraud.md
  examples/components/CCFRAUD/preprocessing/conda.yaml
  examples/components/CCFRAUD/preprocessing/run.py
  examples/components/CCFRAUD/preprocessing/spec.yaml
  examples/components/CCFRAUD/traininsilo/conda.yaml
  examples/components/CCFRAUD/traininsilo/datasets.py
  examples/components/CCFRAUD/traininsilo/models.py
  examples/components/CCFRAUD/traininsilo/run.py
  examples/components/CCFRAUD/traininsilo/spec.yaml
  examples/components/CCFRAUD/upload_data/conda.yaml
  examples/components/CCFRAUD/upload_data/run.py
  examples/components/CCFRAUD/upload_data/spec.yaml
  examples/components/CCFRAUD/upload_data/us_regions.csv
  examples/components/utils/aggregatemodelweights/run.py
  examples/pipelines/ccfraud/config.yaml
  examples/pipelines/ccfraud/submit.py
  examples/pipelines/utils/upload_data/config.yaml
  examples/pipelines/utils/upload_data/submit.py
Labels: iteration-04

#177 Named Entity Recognition example
  docs/README.md
  docs/real-world-examples/ner.md
  examples/components/NER/preprocessing/conda.yaml
  examples/components/NER/preprocessing/run.py
  examples/components/NER/preprocessing/spec.yaml
  examples/components/NER/traininsilo/conda.yaml
  examples/components/NER/traininsilo/labels.json
  examples/components/NER/traininsilo/run.py
  examples/components/NER/traininsilo/spec.yaml
  examples/components/NER/upload_data/conda.yaml
  examples/components/NER/upload_data/run.py
  examples/components/NER/upload_data/spec.yaml
  examples/pipelines/ner/config.yaml
  examples/pipelines/ner/submit.py
  examples/pipelines/utils/upload_data/submit.py
Labels: iteration-04

#190 Create nice-looking homepage for the examples in readme+docs
  README.md
  docs/README.md
  docs/pics/industry-fraud-detection.png
  docs/pics/industry-medical-imaging.png
  docs/pics/industry-ner.png
Labels: documentation
