Repository Azure-Samples/azure-ml-federated-learning, pull requests merged in 2022-09, with the labels that each got.

#48 add integration validation test - build
  .github/workflows/python.yaml
  examples/pipelines/fl_cross_silo_basic/requirements.txt
  requirements.txt
Labels: release-Aug31

#55 To store aggregated models in a single folder
  .github/workflows/python.yaml
  examples/pipelines/fl_cross_silo_basic/submit.py
Labels: iteration-02

#59 Fix optional input yaml and mlflow log bugs
  examples/components/MNIST/aggregatemodelweights/aggregatemodelweights.yaml
  examples/components/MNIST/postprocessing/postprocessing.yaml
  examples/components/MNIST/traininsilo/run.py
  examples/components/MNIST/traininsilo/traininsilo.yaml
Labels: bug

#58 Native bicep provisioning script for vanilla demo setup
  docs/vanilla_demo.md
  examples/components/MNIST/aggregatemodelweights/aggregatemodelweights.yaml
  examples/components/MNIST/traininsilo/traininsilo.yaml
  examples/pipelines/fl_cross_silo_basic/config.yaml
  examples/pipelines/fl_cross_silo_basic/submit.py
  mlops/bicep/modules/orchestrators/orchestrator_with_uai.bicep
  mlops/bicep/modules/roles/role_storage_read_write.bicep
  mlops/bicep/modules/roles/role_storage_write_only.bicep
  mlops/bicep/modules/silos/internal_blob_with_uai.bicep
  mlops/bicep/vanilla_demo_setup.bicep
Labels: auto-provisioning

#67 Create draft documentation folder with homepage and quickstart
  README.md
  docs/README.md
  docs/concepts.md
  docs/provisioning.md
  docs/provisioning/external_silos.md
  docs/provisioning/internal_silos.md
  docs/quickstart.md
  docs/vanilla_demo.md
  examples/pipelines/fl_cross_silo_basic/requirements.txt
  examples/pipelines/fl_cross_silo_basic/submit.py
  examples/requirements.txt
  mlops/README.md
Labels: documentation

#68 Display metrics at the pipeline level
  examples/components/MNIST/postprocessing/postprocessing.yaml
  examples/components/MNIST/preprocessing/conda.yaml
  examples/components/MNIST/preprocessing/preprocessing.yaml
  examples/components/MNIST/preprocessing/run.py
  examples/components/MNIST/traininsilo/run.py
  examples/components/MNIST/traininsilo/traininsilo.yaml
  examples/pipelines/fl_cross_silo_basic/submit.py
Labels: iteration-02

#71 Rename demo script to highlight insecure status
  docs/quickstart.md
  mlops/bicep/open_sandbox_setup.bicep
Labels: documentation

#72 Unified documentation
  .github/workflows/python.yaml
  README.md
  docs/README.md
  docs/concepts.md
  docs/experiment.md
  docs/glossary.md
  docs/guide.md
  docs/milestones.md
  docs/pics/fl_fig.png
  docs/plan.md
  docs/proposal.md
  docs/provisioning.md
  docs/provisioning/external_silos.md
  docs/provisioning/internal_silos.md
  docs/quickstart.md
  examples/pipelines/fl_cross_silo_native/config.yaml
  examples/pipelines/fl_cross_silo_native/environment.yml
  examples/pipelines/fl_cross_silo_native/requirements.txt
  examples/pipelines/fl_cross_silo_native/submit.py
Labels: documentation, iteration-02

#73 Simplify open sandbox setup script
  docs/quickstart.md
  examples/pipelines/fl_cross_silo_native/config.yaml
  mlops/bicep/modules/orchestrators/orchestrator_open.bicep
  mlops/bicep/modules/orchestrators/orchestrator_with_uai.bicep
  mlops/bicep/modules/silos/internal_blob_open.bicep
  mlops/bicep/open_sandbox_setup.bicep
Labels: documentation, auto-provisioning

#76 Document the metrics panel of the pipeline overview in the quickstart
  docs/pics/metrics.PNG
  docs/pics/pipeline-aml.PNG
  docs/quickstart.md
Labels: documentation, iteration-02

#78 Add instructions on how to create a custom graph
  docs/pics/combined-losses-silos.PNG
  docs/quickstart.md
Labels: documentation, iteration-02

#82 Refine native code
  examples/components/MNIST/aggregatemodelweights/run.py
  examples/components/MNIST/traininsilo/run.py
  examples/components/MNIST/traininsilo/traininsilo.yaml
  examples/pipelines/fl_cross_silo_native/config.yaml
  examples/pipelines/fl_cross_silo_native/submit.py
Labels: bug, enhancement, iteration-02

#83 Better description for orchestrator bicep script
  mlops/bicep/modules/orchestrators/orchestrator_open.bicep
Labels: auto-provisioning, iteration-02

#88 Align HelloWorld example with "iteration" naming convention
  examples/components/HELLOWORLD/traininsilo/run.py
  examples/components/HELLOWORLD/traininsilo/traininsilo.yaml
Labels: bug

#86 Make each provisioning script pick-and-choose (can run independently)
  examples/components/HELLOWORLD/traininsilo/run.py
  examples/pipelines/fl_cross_silo_native/config.yaml
  examples/pipelines/fl_cross_silo_native/submit.py
  mlops/bicep/modules/orchestrators/open_orchestrator_blob.bicep
  mlops/bicep/modules/resources/open_azureml_workspace.bicep
  mlops/bicep/modules/roles/role_storage_read_write.bicep
  mlops/bicep/modules/roles/role_storage_write_only.bicep
  mlops/bicep/modules/silos/internal_blob_open.bicep
  mlops/bicep/modules/silos/open_internal_blob.bicep
  mlops/bicep/open_sandbox_setup.bicep
Labels: auto-provisioning

#97 Align config of factory experiment with bicep provisioning names
  examples/pipelines/fl_cross_silo_factory/config.yaml
Labels: bug
