Repository Azure-Samples/azure-ml-federated-learning, pull requests merged in 2022-12, with the labels that each got.

#199 CLI commands to add credentials in the workspace keyvault
  docs/real-world-examples/ccfraud.md
  docs/real-world-examples/pneumonia.md
Labels: documentation, iteration-04

#200 Add GitHub Action workflow concurrency and implement token expiration policy workaround
  .github/actions/submit-aml-factory-pipeline/action.yaml
  .github/actions/submit-aml-literal-pipeline/action.yaml
  .github/actions/submit-example-pipeline/action.yaml
  .github/actions/submit-upload-data-pipeline/action.yaml
  .github/workflows/pipeline-e2e-test.yaml
  .github/workflows/release-branch-test.yaml
  examples/pipelines/ccfraud/submit.py
  examples/pipelines/fl_cross_silo_factory/submit.py
  examples/pipelines/fl_cross_silo_literal/submit.py
  examples/pipelines/ner/submit.py
  examples/pipelines/pneumonia/submit.py
  examples/pipelines/utils/upload_data/submit.py
Labels: testing

#208 Implement troubleshooting guide with first typical issues
  README.md
  docs/README.md
  docs/tsg.md
Labels: documentation

#209 Fix order of precedence for AML workspace references in submit.py
  examples/pipelines/ccfraud/config.yaml
  examples/pipelines/ccfraud/submit.py
  examples/pipelines/fl_cross_silo_factory/config.yaml
  examples/pipelines/fl_cross_silo_factory/submit.py
  examples/pipelines/fl_cross_silo_literal/config.yaml
  examples/pipelines/fl_cross_silo_literal/submit.py
  examples/pipelines/ner/config.yaml
  examples/pipelines/ner/submit.py
  examples/pipelines/pneumonia/config.yaml
  examples/pipelines/pneumonia/submit.py
  examples/pipelines/utils/upload_data/config.yaml
  examples/pipelines/utils/upload_data/submit.py
Labels: bug
