Repository Azure-Samples/azure-ml-federated-learning, pull requests merged in 2023-01, with the labels that each got.

#226 Make scripts run locally
  examples/components/CCFRAUD/preprocessing/run.py
  examples/components/CCFRAUD/traininsilo/run.py
  examples/components/MNIST/preprocessing/run.py
  examples/components/MNIST/traininsilo/run.py
  examples/components/NER/preprocessing/run.py
  examples/components/NER/traininsilo/run.py
  examples/components/PNEUMONIA/traininsilo/run.py
Labels: bug, iteration-05

#188 Provisioning script to create cpu+gpu computes
  .github/actions/provision-resources/action.yaml
  .github/scripts/delete-run-history.sh
  .github/workflows/pipeline-e2e-test.yaml
  examples/pipelines/ccfraud/config.yaml
  examples/pipelines/fl_cross_silo_factory/config.yaml
  examples/pipelines/fl_cross_silo_literal/config.yaml
  examples/pipelines/ner/config.yaml
  examples/pipelines/pneumonia/config.yaml
  examples/pipelines/utils/upload_data/config.yaml
  mlops/arm/open_sandbox_setup.json
  mlops/arm/vnet_compute_existing_storage.json
  mlops/arm/vnet_publicip_sandbox_setup.json
  mlops/bicep/modules/computes/open_new_aml_compute.bicep
  mlops/bicep/modules/computes/vnet_new_aml_compute.bicep
  mlops/bicep/modules/fl_pairs/open_compute_storage_pair.bicep
  mlops/bicep/modules/fl_pairs/vnet_compute_existing_storage.bicep
  mlops/bicep/modules/fl_pairs/vnet_compute_storage_pair.bicep
  mlops/bicep/open_sandbox_setup.bicep
  mlops/bicep/vnet_publicip_sandbox_setup.bicep
Labels: auto-provisioning, iteration-05

#214 CC provisioning and setup
  docs/README.md
  docs/provisioning/silo_open_aks_with_cc.md
  examples/pipelines/ccfraud/submit.py
  examples/pipelines/fl_cross_silo_literal/submit.py
  examples/pipelines/ner/submit.py
  examples/pipelines/pneumonia/submit.py
  mlops/k8s_templates/README.md
  mlops/k8s_templates/instance-type.yaml
Labels: auto-provisioning, iteration-05

#197 POC for DDP training
  docs/real-world-examples/ccfraud.md
  examples/components/CCFRAUD/traininsilo/run.py
  examples/components/CCFRAUD/traininsilo/spec.yaml
  examples/pipelines/ccfraud/config.yaml
  examples/pipelines/ccfraud/submit.py
Labels: enhancement, iteration-05

#232 Change submit to offline with default False
  .github/actions/submit-aml-factory-pipeline/action.yaml
  .github/actions/submit-aml-literal-pipeline/action.yaml
  .github/actions/submit-example-pipeline/action.yaml
  .github/actions/submit-upload-data-pipeline/action.yaml
  .github/workflows/build-test.yaml
  docs/provisioning/external-silos.md
  docs/quickstart.md
  docs/real-world-examples/ccfraud.md
  docs/real-world-examples/ner.md
  docs/real-world-examples/pneumonia.md
  examples/pipelines/ccfraud/submit.py
  examples/pipelines/fl_cross_silo_factory/submit.py
  examples/pipelines/fl_cross_silo_literal/submit.py
  examples/pipelines/ner/submit.py
  examples/pipelines/pneumonia/submit.py
  examples/pipelines/utils/upload_data/submit.py
Labels: enhancement, fl, iteration-05

#233 DDP support for NER + PNEUMONIA
  examples/components/CCFRAUD/traininsilo/run.py
  examples/components/NER/traininsilo/run.py
  examples/components/NER/traininsilo/spec.yaml
  examples/components/PNEUMONIA/traininsilo/run.py
  examples/components/PNEUMONIA/traininsilo/spec.yaml
  examples/pipelines/ccfraud/submit.py
  examples/pipelines/ner/submit.py
  examples/pipelines/pneumonia/submit.py
  mlops/arm/open_sandbox_setup.json
  mlops/arm/vnet_publicip_sandbox_setup.json
Labels: enhancement, fl, iteration-05

#234 Introduce silo names in config files
  examples/pipelines/ccfraud/config.yaml
  examples/pipelines/ccfraud/submit.py
  examples/pipelines/fl_cross_silo_factory/config.yaml
  examples/pipelines/fl_cross_silo_factory/fl_factory.py
  examples/pipelines/fl_cross_silo_factory/submit.py
  examples/pipelines/fl_cross_silo_literal/config.yaml
  examples/pipelines/fl_cross_silo_literal/submit.py
  examples/pipelines/ner/config.yaml
  examples/pipelines/ner/submit.py
  examples/pipelines/pneumonia/config.yaml
  examples/pipelines/pneumonia/submit.py
Labels: enhancement, iteration-05

#225 Support multiple computes in all examples
  examples/pipelines/ccfraud/config.yaml
  examples/pipelines/ccfraud/submit.py
  examples/pipelines/fl_cross_silo_factory/config.yaml
  examples/pipelines/fl_cross_silo_factory/fl_factory.py
  examples/pipelines/fl_cross_silo_factory/submit.py
  examples/pipelines/fl_cross_silo_literal/config.yaml
  examples/pipelines/fl_cross_silo_literal/submit.py
  examples/pipelines/ner/config.yaml
  examples/pipelines/ner/submit.py
  examples/pipelines/pneumonia/config.yaml
  examples/pipelines/pneumonia/submit.py
Labels: enhancement, iteration-05

#247 more precisions about FL vs Silo Admin tasks
  docs/provisioning/external-silos.md
Labels: documentation, iteration-05, direct customer ask

#246 Differential Privacy - MNIST
  docs/quickstart.md
  examples/components/MNIST/traininsilo/conda.yaml
  examples/components/MNIST/traininsilo/run.py
  examples/components/MNIST/traininsilo/spec.yaml
  examples/pipelines/fl_cross_silo_literal/config.yaml
  examples/pipelines/fl_cross_silo_literal/submit.py
  mlops/bicep/open_sandbox_setup.bicep
  mlops/bicep/vnet_publicip_sandbox_setup.bicep
Labels: enhancement, iteration-05

#237 Differential Privacy
  examples/components/CCFRAUD/traininsilo/conda.yaml
  examples/components/CCFRAUD/traininsilo/run.py
  examples/components/CCFRAUD/traininsilo/spec.yaml
  examples/components/HELLOWORLD/traininsilo/run.py
  examples/components/HELLOWORLD/traininsilo/spec.yaml
  examples/components/MNIST/traininsilo/conda.yaml
  examples/components/MNIST/traininsilo/run.py
  examples/components/NER/traininsilo/conda.yaml
  examples/components/NER/traininsilo/run.py
  examples/components/NER/traininsilo/spec.yaml
  examples/components/PNEUMONIA/traininsilo/conda.yaml
  examples/components/PNEUMONIA/traininsilo/run.py
  examples/components/PNEUMONIA/traininsilo/spec.yaml
  examples/pipelines/ccfraud/config.yaml
  examples/pipelines/ccfraud/submit.py
  examples/pipelines/fl_cross_silo_factory/config.yaml
  examples/pipelines/fl_cross_silo_factory/submit.py
  examples/pipelines/fl_cross_silo_literal/config.yaml
  examples/pipelines/ner/config.yaml
  examples/pipelines/ner/submit.py
  examples/pipelines/pneumonia/config.yaml
  examples/pipelines/pneumonia/submit.py
Labels: enhancement, iteration-05

#213 Exploratory Data Analysis (EDA)
  examples/components/utils/data_analysis/run.py
  examples/components/utils/data_analysis/spec.yaml
  examples/pipelines/ccfraud/config.yaml
  examples/pipelines/ccfraud/submit.py
Labels: enhancement, iteration-06
